version: '3.7'

services:
  app-db:
    image: zkot2/postgresdb:v1
    container_name: dev.postgres.db
    ports:
      - "5432:5432"
    networks:
      - app-net
    env_file:
      - ./malaria-apps-env.config
    volumes:
      - 
         type: bind
         source: $POSTGRES_DATA_FILES_VOLUME_SOURCE
         target: $POSTGRES_DATA_FILES_VOLUME_TARGET
  
  data-reader:
    image: zkot2/file-reader.svc:v1
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
    container_name: dev.fsreader.app
    volumes:
      - 
         type: bind
         source: $FS_READER_DATA_VOLUME_SOURCE
         target: $FS_READER_DATA_VOLUME_TARGET
      - 
         type: bind
         source: $FS_READER_COMPLETED_VOLUME_SOURCE
         target: $FS_READER_COMPLETED_VOLUME_TARGET
      - 
         type: bind
         source: $FS_READER_BAD_VOLUME_SOURCE
         target: $FS_READER_BAD_VOLUME_TARGET
      
    depends_on:
      - app-db
    networks:
      - app-net

  api:
    image: zkot2/malaria-data.api:v1
    env_file:
      - ./malaria-apps-env.config
    container_name: dev.malaria-data.api
    ports:
      - "8081:80"
    depends_on:
      - app-db
      - data-reader
    networks:
      - app-net

networks:
  app-net:
    external:
      name: containers_network
